// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieCategory")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieCategory = 0
                        },
                        new
                        {
                            Id = 2,
                            MovieCategory = 1
                        },
                        new
                        {
                            Id = 3,
                            MovieCategory = 2
                        },
                        new
                        {
                            Id = 4,
                            MovieCategory = 3
                        },
                        new
                        {
                            Id = 5,
                            MovieCategory = 4
                        },
                        new
                        {
                            Id = 6,
                            MovieCategory = 5
                        },
                        new
                        {
                            Id = 7,
                            MovieCategory = 7
                        },
                        new
                        {
                            Id = 8,
                            MovieCategory = 8
                        },
                        new
                        {
                            Id = 9,
                            MovieCategory = 9
                        },
                        new
                        {
                            Id = 10,
                            MovieCategory = 10
                        },
                        new
                        {
                            Id = 11,
                            MovieCategory = 11
                        },
                        new
                        {
                            Id = 12,
                            MovieCategory = 12
                        },
                        new
                        {
                            Id = 13,
                            MovieCategory = 13
                        },
                        new
                        {
                            Id = 14,
                            MovieCategory = 14
                        },
                        new
                        {
                            Id = 15,
                            MovieCategory = 15
                        },
                        new
                        {
                            Id = 16,
                            MovieCategory = 16
                        },
                        new
                        {
                            Id = 17,
                            MovieCategory = 17
                        },
                        new
                        {
                            Id = 18,
                            MovieCategory = 18
                        },
                        new
                        {
                            Id = 19,
                            MovieCategory = 19
                        },
                        new
                        {
                            Id = 20,
                            MovieCategory = 20
                        },
                        new
                        {
                            Id = 21,
                            MovieCategory = 21
                        },
                        new
                        {
                            Id = 22,
                            MovieCategory = 22
                        },
                        new
                        {
                            Id = 23,
                            MovieCategory = 23
                        },
                        new
                        {
                            Id = 24,
                            MovieCategory = 24
                        },
                        new
                        {
                            Id = 25,
                            MovieCategory = 25
                        },
                        new
                        {
                            Id = 26,
                            MovieCategory = 26
                        });
                });

            modelBuilder.Entity("Entities.Movie", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BannerURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("IMDBstar")
                        .HasColumnType("float");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieLength")
                        .HasColumnType("int");

                    b.Property<string>("Plot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailerURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = "tt0218839",
                            BannerURL = "https://m.media-amazon.com/images/M/MV5BMTQ5OTc0NDU1MF5BMl5BanBnXkFtZTYwNzk1OTI3._V1_.jpg",
                            ContentRating = "PG-13",
                            Description = "At the prestigious Mayflower Dog Show, a \"documentary film crew\" captures the excitement and tension displayed by the eccentric participants in the outrageously hilarious satire Best In Show. This biting send-up exposes the wondrously diverse dog owners who travel from all over America to showcase their four-legged contenders. Mild-mannered salesman Gerry Fleck (Eugene Levy) and his vivacious wife, Cookie (Catherine O'Hara), happily prepare their Norwich Terrier, while shop owner Harlan Pepper (Christopher Guest) hopes his Bloodhound wins top prize. As two upwardly mobile attorneys (Parker Posey and Michael Hitchcock) anxiously ready their neurotic Weimaraner and an ecstatically happy gay couple (Michael McKean and John Michael Higgins) dote on their tiny Shih Tzu, inept commentator Buck Laughlin (Fred Willard) vainly attempts to provide colorful tidbits about each breed.",
                            IMDBstar = 7.5,
                            ImageURL = "https://m.media-amazon.com/images/M/MV5BMTQ5OTc0NDU1MF5BMl5BanBnXkFtZTYwNzk1OTI3._V1_UX182_CR0,0,182,268_AL_.jpg",
                            MovieLength = 90,
                            Plot = "A behind-the-scenes look into the highly competitive and cut-throat world of dog shows through the eyes of a group of ruthless dog owners.",
                            Title = "Best in Show",
                            TrailerURL = "https://www.youtube.com/embed/94y9n9lNy2Y",
                            Year = 2000
                        },
                        new
                        {
                            Id = "tt0204946",
                            BannerURL = "https://m.media-amazon.com/images/M/MV5BNjhiMjk1YWYtMjgyYy00YTFhLTk0NTMtN2Q5MDZjMWEyYWI1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
                            ContentRating = "PG-13",
                            Description = "The Toro cheerleading squad from Rancho Carne High School in San Diego has got spirit, spunk, sass and a killer routine that's sure to land them the national championship trophy for the sixth year in a row. But for newly-elected team captain Torrance, the Toros' road to total cheer glory takes a shady turn when she discovers that their perfectly-choreographed routines were in fact stolen from the Clovers, a hip-hop squad from East Compton, by the Toro's former captain. While the Toros scramble to come up with a new routine, the Clovers, led by squad captain Isis have their own problems - coming up with enough money to cover their travel expenses to the championships. With time running out and the pressure mounting, both captains drive their squads to the point of exhaustion: Torrance, hell bent on saving the Toros' reputation, and Isis more determined than ever to see that the Clovers finally get the recognition that they deserve. But only one team can bring home the title, so may the...",
                            IMDBstar = 6.0,
                            ImageURL = "https://m.media-amazon.com/images/M/MV5BNjhiMjk1YWYtMjgyYy00YTFhLTk0NTMtN2Q5MDZjMWEyYWI1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg",
                            MovieLength = 90,
                            Plot = "A champion high school cheerleading squad discovers its previous captain stole all their best routines from an inner-city school and must scramble to compete at this year's championships.",
                            Title = "Bring It On",
                            TrailerURL = "https://www.youtube.com/embed/Pg0UYb8U2Dg",
                            Year = 2000
                        },
                        new
                        {
                            Id = "tt0181875",
                            BannerURL = "https://m.media-amazon.com/images/M/MV5BMzY1ZjMwMGEtYTY1ZS00ZDllLTk0ZmUtYzA3ZTA4NmYwNGNkXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg",
                            ContentRating = "R",
                            Description = "The early 1970s. William Miller is 15-years old and an aspiring rock journalist. He gets a job writing for Rolling Stone magazine. His first assignment: tour with the band Stillwater and write about the experience. Miller will get to see what goes on behind the scenes in a famous band, including the moments when things fall apart. Moreover, for him, it will be a period of new experiences and finding himself.",
                            IMDBstar = 7.9000000000000004,
                            ImageURL = "https://m.media-amazon.com/images/M/MV5BMzY1ZjMwMGEtYTY1ZS00ZDllLTk0ZmUtYzA3ZTA4NmYwNGNkXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_UX182_CR0,0,182,268_AL_.jpg",
                            MovieLength = 98,
                            Plot = "A high-school boy is given the chance to write a story for Rolling Stone Magazine about an up-and-coming rock band as he accompanies them on their concert tour.",
                            Title = "Almost Famous",
                            TrailerURL = "https://www.youtube.com/embed/aQXh_AaJXaM",
                            Year = 2000
                        },
                        new
                        {
                            Id = "tt0187078",
                            BannerURL = "https://m.media-amazon.com/images/M/MV5BMTIwMzExNDEwN15BMl5BanBnXkFtZTYwODMxMzg2._V1_.jpg",
                            ContentRating = "PG-13",
                            Description = "In exchange for his little brother's life, the reformed car thief, Randall \"Memphis\" Raines, has to do the impossible: in less than three days, he has to steal not one, but fifty exotic supercars for the ruthless crime lord, Ray Calitri. To stand a chance of pulling off this intricate and time-sensitive grand theft auto, once more, Memphis has to rely on his old gang--his knowledgeable mentor, Otto; the old friends, Sphinx and Donny; his reluctant ex-girlfriend, Sway, and a band of tech-savvy young thieves--however, the police are already onto them. Now, fast Lamborghinis, precious Ferraris, luxurious Porsches, and Eleanor--a rare Ford Shelby Mustang GT500--are just some of the cars in Raines' long list. Can Memphis execute the perfect car heist?",
                            IMDBstar = 6.5,
                            ImageURL = "https://m.media-amazon.com/images/M/MV5BMTIwMzExNDEwN15BMl5BanBnXkFtZTYwODMxMzg2._V1_UX182_CR0,0,182,268_AL_.jpg",
                            MovieLength = 118,
                            Plot = "A retired master car thief must come back to the industry and steal fifty cars with his crew in one night to save his brother's life.",
                            Title = "Gone in Sixty Seconds",
                            TrailerURL = "https://www.youtube.com/embed/ap5RqRzjS6g",
                            Year = 2000
                        },
                        new
                        {
                            Id = "tt0175142",
                            BannerURL = "https://m.media-amazon.com/images/M/MV5BMGEzZjdjMGQtZmYzZC00N2I4LThiY2QtNWY5ZmQ3M2ExZmM4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
                            ContentRating = "R",
                            Description = "A group of teenagers including Cindy Campbell and Bobby Prinze, accidentally hit a man when driving, and dispose of the body, but now they are being stalked by a very recognisable masked killer. The victim count increases, whilst Cindy must survive the carnage that has she has seen in so many films before.",
                            IMDBstar = 6.2000000000000002,
                            ImageURL = "https://m.media-amazon.com/images/M/MV5BMGEzZjdjMGQtZmYzZC00N2I4LThiY2QtNWY5ZmQ3M2ExZmM4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg",
                            MovieLength = 88,
                            Plot = "A year after disposing of the body of a man they accidentally killed, a group of dumb teenagers are stalked by a bumbling serial killer.",
                            Title = "Scary Movie",
                            TrailerURL = "https://www.youtube.com/embed/SzpGYrrcJZw",
                            Year = 2000
                        },
                        new
                        {
                            Id = "tt0210945",
                            BannerURL = "https://m.media-amazon.com/images/M/MV5BYThkMzgxNjEtMzFiOC00MTI0LWI5MDItNDVmYjA4NzY5MDQ2L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
                            ContentRating = "PG",
                            Description = "Suburban Virginia schools have been segregated for generations. One Black and one White high school are closed and the students sent to T.C. Williams High School under federal mandate to integrate. The year is seen through the eyes of the football team where the man hired to coach the Black school is made head coach over the highly successful white coach. Based on the actual events of 1971, the team becomes the unifying symbol for the community as the boys and the adults learn to depend on and trust each other.",
                            IMDBstar = 7.7999999999999998,
                            ImageURL = "https://m.media-amazon.com/images/M/MV5BYThkMzgxNjEtMzFiOC00MTI0LWI5MDItNDVmYjA4NzY5MDQ2L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg",
                            MovieLength = 113,
                            Plot = "The true story of a newly appointed African-American coach and his high school team on their first season as a racially integrated unit.",
                            Title = "Remember the Titans",
                            TrailerURL = "https://www.youtube.com/embed/35MvdHBWjwU",
                            Year = 2000
                        },
                        new
                        {
                            Id = "tt0190590",
                            BannerURL = "https://m.media-amazon.com/images/M/MV5BMjZkOTdmMWItOTkyNy00MDdjLTlhNTQtYzU3MzdhZjA0ZDEyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
                            ContentRating = "PG-13",
                            Description = "Loosely based on Homer's \"Odyssey,\" the movie deals with the picaresque adventures of Ulysses Everett McGill and his companions Delmar and Pete in 1930s Mississipi. Sprung from a chain gang and trying to reach Everett's home to recover the buried loot of a bank heist they are confronted by a series of strange characters--among them sirens, a cyclops, bank robber George \"Baby Face\" Nelson (very annoyed by that nickname), a campaigning governor and his opponent, a KKK lynch mob, and a blind prophet who warns the trio that \"the treasure you seek shall not be the treasure you find.\"",
                            IMDBstar = 7.7000000000000002,
                            ImageURL = "https://m.media-amazon.com/images/M/MV5BMjZkOTdmMWItOTkyNy00MDdjLTlhNTQtYzU3MzdhZjA0ZDEyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX182_CR0,0,182,268_AL_.jpg",
                            MovieLength = 107,
                            Plot = "In the deep south during the 1930s, three escaped convicts search for hidden treasure while a relentless lawman pursues them.",
                            Title = "O Brother, Where Art Thou?",
                            TrailerURL = "https://www.youtube.com/embed/eW9Xo2HtlJI",
                            Year = 2000
                        });
                });

            modelBuilder.Entity("Entities.MovieCategory", b =>
                {
                    b.Property<string>("MovieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MovieCategories");

                    b.HasData(
                        new
                        {
                            MovieId = "tt0218839",
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = "tt0204946",
                            CategoryId = 6
                        },
                        new
                        {
                            MovieId = "tt0204946",
                            CategoryId = 8
                        },
                        new
                        {
                            MovieId = "tt0204946",
                            CategoryId = 13
                        },
                        new
                        {
                            MovieId = "tt0181875",
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = "tt0181875",
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = "tt0181875",
                            CategoryId = 6
                        },
                        new
                        {
                            MovieId = "tt0181875",
                            CategoryId = 19
                        },
                        new
                        {
                            MovieId = "tt0187078",
                            CategoryId = 4
                        },
                        new
                        {
                            MovieId = "tt0187078",
                            CategoryId = 9
                        },
                        new
                        {
                            MovieId = "tt0187078",
                            CategoryId = 10
                        },
                        new
                        {
                            MovieId = "tt0175142",
                            CategoryId = 6
                        },
                        new
                        {
                            MovieId = "tt0210945",
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = "tt0210945",
                            CategoryId = 8
                        },
                        new
                        {
                            MovieId = "tt0210945",
                            CategoryId = 14
                        },
                        new
                        {
                            MovieId = "tt0190590",
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = "tt0190590",
                            CategoryId = 4
                        },
                        new
                        {
                            MovieId = "tt0190590",
                            CategoryId = 6
                        },
                        new
                        {
                            MovieId = "tt0190590",
                            CategoryId = 19
                        });
                });

            modelBuilder.Entity("Entities.MovieReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Star")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("MoviesReviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tincidunt molestie massa quis vulputate. Pellentesque mollis egestas lectus, in tempus lorem scelerisque vitae. Donec fermentum quam nec ligula sollicitudin, quis tincidunt orci laoreet. Donec ut tincidunt tortor. Integer eget neque pellentesque risus varius gravida ac sit amet augue. Morbi tristique risus nec augue venenatis, id viverra dolor lobortis. Curabitur malesuada enim libero, nec tincidunt sem varius at. Proin id auctor magna, in pellentesque quam. In hac habitasse platea dictumst. Donec suscipit rutrum risus. Maecenas tristique lorem et nisl ullamcorper, at iaculis nisl laoreet. Etiam sed gravida felis, quis fringilla nisi. Maecenas in urna dolor. Nullam tincidunt varius vestibulum.",
                            MovieId = "tt0218839",
                            Star = 10,
                            Title = "Flawless",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1992, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "husnu.cemre@gmail.com",
                            Name = "Hüsnü Cemre",
                            NickName = "trc10",
                            Password = "123Abc."
                        });
                });

            modelBuilder.Entity("Entities.UserReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewedUserId")
                        .HasColumnType("int");

                    b.Property<double>("Star")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ReviewedUserId");

                    b.ToTable("UserReviews");
                });

            modelBuilder.Entity("Entities.MovieCategory", b =>
                {
                    b.HasOne("Entities.Category", "Category")
                        .WithMany("MovieCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Movie", "Movie")
                        .WithMany("MovieCategories")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Entities.MovieReview", b =>
                {
                    b.HasOne("Entities.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.User", "User")
                        .WithMany("MovieReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.UserReview", b =>
                {
                    b.HasOne("Entities.User", "Author")
                        .WithMany("UserReviews")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.User", "ReviewedUser")
                        .WithMany()
                        .HasForeignKey("ReviewedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ReviewedUser");
                });

            modelBuilder.Entity("Entities.Category", b =>
                {
                    b.Navigation("MovieCategories");
                });

            modelBuilder.Entity("Entities.Movie", b =>
                {
                    b.Navigation("MovieCategories");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Navigation("MovieReviews");

                    b.Navigation("UserReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
